name: Automation Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  automation-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Run API Test
        run: ./gradlew apiTest
        continue-on-error: true

      - name: Run Web Test
        run: ./gradlew webTest
        continue-on-error: true

      - name: Upload API Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-cucumber-report
          path: reports/api-report.*
          retention-days: 30

      - name: Upload Web Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-cucumber-report
          path: reports/web-report.*
          retention-days: 30